# -*- coding: utf-8 -*-
"""
Created on Fri Mar 24 16:44:59 2017

@author: natasha1_Yang
"""

MSG_TYPE = "TYPE"
REGISTER = "REGISTER"
UNREGISTER = "UNREGISTER"
HEARTBEAT = "HEARTBETA"
PAUSED = "PAUSED"
RESUMED = "RESUMED"
SHUTDOWN = "SHUTDOWN"
CLIENT_ID = "CLIENT_ID"
ACTION_REQUIRED = "ACTION_REQUIRED"
PAUSE_REQUIRED = "PAUSE_REQUIRED"
RESUME_REQUIRED = 'RESUME_REQUIRED'
SHUTDOWN_REQUIRED = 'SHUTDOWN_REQUIRED'
SERVER_STATUS = 'SERVER_STATUS'
STATUS_RUNNING	= 'STATUS_RUNNING'
STATUS_PAUSED = 'STATUS_PAUSED'
STATUS_SHUTDOWN = 'STATUS_SHUTDOWN'
STATUS_CONNECTION_LOST = 'STATUS_CONNECTION_LOST'
ERROR = 'ERROR'
ERR_NOT_FOUND = 'ERR_NOT_FOUND'